/**
 * data.js
 * Contains static content and data structures used by the application.
 */

export const imageGallery = [
    'deer.jpg', 'gym_pic.jpg', 'ice_cave.JPG',
    'ice_wings.JPG', 'nyc.jpg', 'pirate.jpg', 'riverwalk.jpg', 'surfing.JPG'
];

export const allDescribableCourses = [
    // Advanced Placement Credits
    { name: 'CSE 1300: Intro to Computing Principles', institution: 'Milton Highschool (MHS)', term: 'AP Credit', description: 'General introduction to computing principles, often covering basic hardware, software concepts, algorithmic thinking, and an overview of the impact of computers on society.' },
    { name: 'CSE 1321: Programming Problem Solving I', institution: 'Milton Highschool (MHS)', term: 'AP Credit', description: 'Introduction to programming problem solving, typically covering fundamental programming constructs like variables, control structures (loops, conditionals), data types, and an introduction to object-oriented concepts or procedural programming. Often taught using a language like Java or C++.' },
    { name: 'CSE 1321L: Program Problem Solving I Lab', institution: 'Milton Highschool (MHS)', term: 'AP Credit', description: 'Laboratory component for an introductory programming course, providing hands-on practice with the concepts taught in the lecture, involving coding exercises and small projects.' },
    { name: 'ECON 2200: Principles of Economics-Macro', institution: 'Milton Highschool (MHS)', term: 'AP Credit', description: 'Introduction to macroeconomic principles, covering topics like national income, inflation, unemployment, fiscal policy, monetary policy, and economic growth.' },
    { name: 'MATH 1113: Precalculus', institution: 'Milton Highschool (MHS)', term: 'AP Credit', description: 'Covers topics in algebra and trigonometry essential for calculus, including functions, graphing, logarithms, exponents, trigonometric functions, identities, and equations.' },
    { name: 'MATH 1190: Calculus I', institution: 'Milton Highschool (MHS)', term: 'AP Credit', description: 'Introduction to differential calculus, including limits, continuity, derivatives of algebraic and transcendental functions, and applications of derivatives such as optimization and related rates. May also include an introduction to integration.' },
    { name: 'PSYC 1101: Introductory Psychology', institution: 'Milton Highschool (MHS)', term: 'AP Credit', description: 'Broad overview of the field of psychology, covering major topics such as research methods, biological bases of behavior, sensation and perception, learning, memory, motivation, emotion, development, personality, psychological disorders, and social psychology.' },
    { name: 'SCI 1102: Science, Society & Environ II', institution: 'Milton Highschool (MHS)', term: 'AP Credit', description: 'An interdisciplinary science course focusing on the relationship between science, society, and the environment. May cover topics such as ecological principles, environmental issues, resource management, and the scientific process in addressing societal challenges.' },
    // University of North Georgia
    { name: 'ENGL 1101: English Composition I', institution: 'University of North Georgia:', term: 'Fall 2018', description: 'Based on general catalog information, this course focuses on developing academic and professional written communication through a variety of rhetorical strategies. It emphasizes critical thinking, analysis, and introductory academic research skills.' },
    { name: 'HIST 2111: American History I', institution: 'University of North Georgia:', term: 'Fall 2018', description: 'This course typically surveys United States history from exploration and colonization through the Reconstruction era, emphasizing the social, cultural, political, and economic evolution of the U.S.' },
    { name: 'PHIL 2200: Global Ethics', institution: 'University of North Georgia:', term: 'Fall 2018', description: 'This course introduces the student to the major, traditional ethical theories, their foundational arguments, strengths, weaknesses, and meaning for life as lived. The course explores both the major Western and Non-western ethical theories.' },
    { name: 'POLS 1101: American Government', institution: 'University of North Georgia:', term: 'Fall 2018', description: 'An introductory course that provides an overview of the Constitutional foundations of the nation, government institutions, and political processes. It generally also satisfies legislative requirements concerning the United States and Georgia Constitutions.' },
    // Kennesaw State University (KSU)
    { name: 'CSE 1322: Programming Problem Solving II', institution: 'Kennesaw State University (KSU):', term: 'Spring 2020 (GPA: 3.75)', description: 'The second course in computing provides coverage of advanced topics in programming. This includes the use of inheritance and polymorphism, abstract classes and interfaces, file input/output, exception handling, recursion, and parameterized types. Linear data structures (lists, stacks, and queues) are introduced to solve a variety of problems. Concepts related to the design of programs using Graphical User Interfaces (GUIs), event-driven programming, and threaded and parallel programming, are also introduced. Students will use good programming style including proper documentation.' },
    { name: 'CSE 1322L: Program Problem Solving II Lab', institution: 'Kennesaw State University (KSU):', term: 'Spring 2020 (GPA: 3.75)', description: 'The second lab course in computer science provides coverage of more advanced topics of object-oriented programming practices. This includes the use of static variables and classes, multi-dimensional arrays, inheritance and polymorphism, text files and exception handling, recursion, and parameterized types. Elementary data structures (linked lists, stacks, and queues) are introduced to solve application problems. Graphical user interfaces and event driven programming are also introduced. Students must continue to use good programming style including proper documentation.' },
    { name: 'ECON 1000: Contemporary Economic Issues', institution: 'Kennesaw State University (KSU):', term: 'Spring 2020 (GPA: 3.75)', description: 'This course provides students with the knowledge and tools necessary to critically examine social and policy issues from an economic perspective. Fundamental economic questions – as they relate to individuals, firms, and society in the modern global world – are addressed. Students learn about different economic systems, how markets function, the role of government in the economy, the basis for international trade, measurement of macroeconomic performance, and the impact of globalization on living standards and economic growth.' },
    { name: 'HIST 1112: Modern World History', institution: 'Kennesaw State University (KSU):', term: 'Spring 2020 (GPA: 3.75)', description: 'A survey of World History from early modern times (approx. 1500) to the present. It provides an introduction to the origin and development of the world\'s societies and their political, cultural, and economic traditions.' },
    { name: 'STAT 1401: Elementary Statistics', institution: 'Kennesaw State University (KSU):', term: 'Spring 2020 (GPA: 3.75)', description: 'This is a non-calculus based introduction to statistics. Course content includes descriptive statistics, probability theory, confidence intervals, hypothesis testing, and other selected statistical topics.' },
    { name: 'CS 3503: Computer Organization & Arch', institution: 'Kennesaw State University (KSU):', term: 'Fall 2020 (GPA: 3.75)', description: 'An introduction to the theory and fundamentals of computer organization and architecture. The course covers computer architecture which overviews the structure and operational units of the computer used to implement a software program. Topics include data representation and encoding, binary arithmetic, fixed- and floating-point representation, numbering systems, error-control, instruction set architecture, assembly language and programming, microcode, memory organization and addressing, I/O, interrupts, internal architecture, instruction pipelining, multi-core architectures and CPU/ALU basics. The course also covers computer organization which overviews the computer\'s fundamental building blocks, hardware units, and their interconnection. Topics include Boolean algebra, logic gates, flip-flops, counters, registers, combinational and sequential circuits, K-maps, circuit design, and various digital components.' },
    { name: 'MATH 2345: Discrete Mathematics', institution: 'Kennesaw State University (KSU):', term: 'Fall 2020 (GPA: 3.75)', description: 'An introduction to the fundamentals of discrete mathematics. Topics include sets, formal logic, methods of proof, counting relations, functions, graphs and trees, and finite state automata.' },
    { name: 'PHIL 2010: Intro to Philosophy', institution: 'Kennesaw State University (KSU):', term: 'Fall 2020 (GPA: 3.75)', description: 'This course provides an Introduction to the central issues, questions, and theories of Western Philosophy. Topics covered include logic & critical thinking; religion; knowledge & skepticism; philosophy of mind; freedom and determinism; and ethics.' },
    { name: 'STAT 3010: Computer Appl. of Statistics', institution: 'Kennesaw State University (KSU):', term: 'Fall 2020 (GPA: 3.75)', description: 'This course is an introduction to the use of computer-based statistical software packages and applications in the analysis and interpretation of data. Topics include both descriptive statistics and inference methods. Software packages include SAS, Excel, and R, and one of JMP, SPSS, or Minitab.' },
    // University of South Florida (USF)
    { name: 'LIS 2005: Information Literacy', institution: 'University of South Florida (USF):', term: 'Fall 2022 (GPA: 3.5)', description: 'This course covers the development of undergraduate research and critical thinking skills to identify, evaluate, and use appropriate information sources to address educational, research, and other information needs. It teaches you how to find a research topic, identify keywords, use search engines better, use the USF online library including how to use databases, how to evaluate information, how to use the information you find in a research paper and how to cite that information correctly.' },
    { name: 'LIS 3261: Intro to Information Science', institution: 'University of South Florida (USF):', term: 'Fall 2022 (GPA: 3.5)', description: 'Introduces the major concepts, principles, theories, issues and trends in information science.' },
    { name: 'LIS 4273: Adv Stats & Analytics', institution: 'University of South Florida (USF):', term: 'Fall 2022 (GPA: 3.5)', description: 'Building on elementary statistics, this course focuses on the assumptions, mechanisms, and data science applications for advanced statistical topics, such as logistic regression, maximum likelihood, bootstrapping, nonparametrics, & Bayesian methods.' },
    { name: 'MUC 2301: Intro to Electronic Music', institution: 'University of South Florida (USF):', term: 'Fall 2022 (GPA: 3.5)', description: 'A study of the past century\'s technological explosion, which has affected the way in which music is performed, recorded, edited, composed, distributed, reproduced, and perceived worldwide. This course affords students the ability to think critically and includes selections from the western canon.' },
    { name: 'CIS 3360: Prin of Information Security', institution: 'University of South Florida (USF):', term: 'Spring 2023 (GPA: 4.0)', description: 'This course provides an overview of information systems security principles, practices, methods, and tools for organizational and institutional computing. Students will learn about the relationship between policy and security, the mechanisms used to implement policies, and the methodologies and technologies for assurance and vulnerability analysis and intrusion detection. It includes terminology, history of the discipline, overview of information security program management.' },
    { name: 'ENC 1102: Composition II', institution: 'University of South Florida (USF):', term: 'Spring 2023 (GPA: 4.0)', description: 'This course emphasizes argument, research, and style. As students engage in creative and critical thinking, they learn to support assertions based on audience and purpose; students apply library research, strategies for revision, and peer response. Instruction and practice in the skills of writing and reading. This course affords students the ability to communicate effectively, including the ability to write clearly and engage in public speaking.' },
    { name: 'LIS 2780: Database Concepts', institution: 'University of South Florida (USF):', term: 'Spring 2023 (GPA: 4.0)', description: 'This course examines Relational Database Management Systems using a typical commercial DBMS, such as Microsoft Access. Data modeling, database design, implementation, forms and reports, and remote access to databases are covered. Also covers Structured Query Language (SQL).' },
    { name: 'LIS 3353: IT Concepts/Info Professionals', institution: 'University of South Florida (USF):', term: 'Spring 2023 (GPA: 4.0)', description: 'This course provides a fundamental understanding of Information Technology (IT) concepts and their practical application in various professional settings. Topics typically include hardware, software, networking, databases, cybersecurity, and current IT trends, geared towards information professionals.' },
    { name: 'LIS 3361: WWW Page Design/Management', institution: 'University of South Florida (USF):', term: 'Spring 2023 (GPA: 4.0)', description: 'Covers the principles of web page design and website management. Students learn to create and maintain websites using HTML, CSS, and potentially content management systems. Emphasis on usability, accessibility, and information architecture.' },
    { name: 'COP 2250: Obj. Orient Program (Java SE)', institution: 'University of South Florida (USF):', term: 'Summer 2023 (GPA: 3.89)', description: 'Introduction to object-oriented programming using the Java Standard Edition (SE) platform. Topics include classes, objects, inheritance, polymorphism, exception handling, and basic data structures. Focus on developing problem-solving skills through programming.' },
    { name: 'ENC 3250: Professional Writing', institution: 'University of South Florida (USF):', term: 'Summer 2023 (GPA: 3.89)', description: 'Focuses on the types of writing common in professional settings. Students learn to analyze audience and purpose, develop clear and concise writing styles, and create documents such as memos, reports, proposals, and professional correspondence. Emphasis on rhetoric in professional contexts.' },
    { name: 'HSC 2130: Sex, Health, & Decision-Making', institution: 'University of South Florida (USF):', term: 'Summer 2023 (GPA: 3.89)', description: 'This course explores various aspects of human sexuality, reproductive health, and the decision-making processes related to personal health and relationships. Topics may include STIs, contraception, healthy relationships, and public health issues.' },
    { name: 'ART 2500C: Beginning Painting', institution: 'University of South Florida (USF):', term: 'Fall 2023 (GPA: 4.0)', description: 'An introduction to the fundamental concepts and techniques of painting. Students explore color theory, composition, paint application, and various painting media. Emphasis on developing observational skills and creative expression.' },
    { name: 'LIS 4204: Information Behaviors', institution: 'University of South Florida (USF):', term: 'Fall 2023 (GPA: 4.0)', description: 'Examines the theories and models of how people seek, use, and interact with information in different contexts. Topics include information needs, seeking strategies, user studies, and the impact of technology on information behavior.' },
    { name: 'LIS 4414: Information Policy and Ethics', institution: 'University of South Florida (USF):', term: 'Fall 2023 (GPA: 4.0)', description: 'This course explores the legal, ethical, and societal issues related to information access and use. Topics include privacy, intellectual property, censorship, freedom of information, and the impact of information technologies on policy and ethics.' },
    { name: 'LIS 4482: Networks and Communication', institution: 'University of South Florida (USF):', term: 'Fall 2023 (GPA: 4.0)', description: 'Introduction to data communication and networking concepts. Covers network architectures, protocols, hardware, software, and security. Topics may include LANs, WANs, the Internet, and wireless networking, relevant to information professionals.' },
    { name: 'MUS 2304: Intro to DJ', institution: 'University of South Florida (USF):', term: 'Fall 2023 (GPA: 4.0)', description: 'An introductory course to the art and techniques of DJing. Students learn about equipment, mixing, beatmatching, music selection, and performance aspects of DJ culture.' },
    { name: 'LIS 3352: Interaction Design', institution: 'University of South Florida (USF):', term: 'Spring 2024 (GPA: 3.83)', description: 'This course provides students with an opportunity to acquire the resources, skills, and hands-on experience they need to design, develop, and evaluate information interfaces from a user-centered design perspective. It is the design of the interaction between users, systems and products, often with a focus on user experience (UX) and human-centered design.' },
    { name: 'LIS 3783: Information Architecture', institution: 'University of South Florida (USF):', term: 'Spring 2024 (GPA: 3.83)', description: 'Covers design, organization, implementation, and maintenance of digital information spaces for human access, navigation, and use. Examines core concepts and dominating technologies in Information Architecture. It provides an overview of the information architecture design process, from assessing user needs, through organizing information resources, to documenting the design of information systems and spaces.' },
    { name: 'LIS 4365: Web Design Technologies', institution: 'University of South Florida (USF):', term: 'Spring 2024 (GPA: 3.83)', description: 'This course will focus on two central web programming languages, JavaScript and PHP. In this class we will also learn open source MySQL as a database for the web. You will learn how to critically evaluate website quality; learn how to create and maintain a web page that connects and stores its data to the database; and learn how to display the results from a database display query. Exploration of advanced applications of key Web Technologies.' },
    { name: 'LIS 4934: BSIS Senior Capstone', institution: 'University of South Florida (USF):', term: 'Spring 2024 (GPA: 3.83)', description: 'A culmination and application of Information Studies concepts and acquired skill sets. Students will be immersed in an exploration of contemporary issues that face information professionals. This course is designed to allow students to synthesize knowledge from their undergraduate coursework.' },
    { name: 'PEM 2930: Yoga', institution: 'University of South Florida (USF):', term: 'Spring 2024 (GPA: 3.83)', description: 'Activities offered are selected to reflect student need and faculty interest. Yoga is designed to introduce students to yoga. The class includes theory and physical practice of body position, breathing and meditation.' },
];